import {GENERATED_CONSTANTS} from './generated-constants'

export const CONSTANTS = {
	BACKEND_URL: `${GENERATED_CONSTANTS.BACKEND_PROTOCOL}://${GENERATED_CONSTANTS.BACKEND_HOSTNAME}:${GENERATED_CONSTANTS.BACKEND_PORT}`,
	APP_NAME: "Asian Food Legit",
}
